// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: voicekit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioEncoding int32

const (
	AudioEncoding_ENCODING_UNSPECIFIED AudioEncoding = 0
	AudioEncoding_LINEAR16             AudioEncoding = 1
	AudioEncoding_MULAW                AudioEncoding = 2
	AudioEncoding_ALAW                 AudioEncoding = 3
	AudioEncoding_RAW_OPUS             AudioEncoding = 4
	AudioEncoding_MPEG_AUDIO           AudioEncoding = 5
	AudioEncoding_ADTS_AAC             AudioEncoding = 6
)

// Enum value maps for AudioEncoding.
var (
	AudioEncoding_name = map[int32]string{
		0: "ENCODING_UNSPECIFIED",
		1: "LINEAR16",
		2: "MULAW",
		3: "ALAW",
		4: "RAW_OPUS",
		5: "MPEG_AUDIO",
		6: "ADTS_AAC",
	}
	AudioEncoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"LINEAR16":             1,
		"MULAW":                2,
		"ALAW":                 3,
		"RAW_OPUS":             4,
		"MPEG_AUDIO":           5,
		"ADTS_AAC":             6,
	}
)

func (x AudioEncoding) Enum() *AudioEncoding {
	p := new(AudioEncoding)
	*p = x
	return p
}

func (x AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_voicekit_proto_enumTypes[0].Descriptor()
}

func (AudioEncoding) Type() protoreflect.EnumType {
	return &file_voicekit_proto_enumTypes[0]
}

func (x AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioEncoding.Descriptor instead.
func (AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_voicekit_proto_rawDescGZIP(), []int{0}
}

type RecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StreamingRequest:
	//
	//	*RecognizeRequest_Config
	//	*RecognizeRequest_AudioContent
	StreamingRequest isRecognizeRequest_StreamingRequest `protobuf_oneof:"streaming_request"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_voicekit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voicekit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_voicekit_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeRequest) GetStreamingRequest() isRecognizeRequest_StreamingRequest {
	if x != nil {
		return x.StreamingRequest
	}
	return nil
}

func (x *RecognizeRequest) GetConfig() *StreamingConfig {
	if x != nil {
		if x, ok := x.StreamingRequest.(*RecognizeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *RecognizeRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.StreamingRequest.(*RecognizeRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

type isRecognizeRequest_StreamingRequest interface {
	isRecognizeRequest_StreamingRequest()
}

type RecognizeRequest_Config struct {
	Config *StreamingConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type RecognizeRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"`
}

func (*RecognizeRequest_Config) isRecognizeRequest_StreamingRequest() {}

func (*RecognizeRequest_AudioContent) isRecognizeRequest_StreamingRequest() {}

type StreamingConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Encoding          AudioEncoding          `protobuf:"varint,1,opt,name=encoding,proto3,enum=voicekit.recognizer.v1.AudioEncoding" json:"encoding,omitempty"`
	SampleRate        int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	AudioChannelCount int32                  `protobuf:"varint,3,opt,name=audio_channel_count,json=audioChannelCount,proto3" json:"audio_channel_count,omitempty"`
	LanguageCode      string                 `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamingConfig) Reset() {
	*x = StreamingConfig{}
	mi := &file_voicekit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingConfig) ProtoMessage() {}

func (x *StreamingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voicekit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingConfig.ProtoReflect.Descriptor instead.
func (*StreamingConfig) Descriptor() ([]byte, []int) {
	return file_voicekit_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingConfig) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_ENCODING_UNSPECIFIED
}

func (x *StreamingConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *StreamingConfig) GetAudioChannelCount() int32 {
	if x != nil {
		return x.AudioChannelCount
	}
	return 0
}

func (x *StreamingConfig) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

type RecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Transcript          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_voicekit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voicekit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_voicekit_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeResponse) GetResults() []*Transcript {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RecognizeResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type Transcript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_voicekit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_voicekit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_voicekit_proto_rawDescGZIP(), []int{3}
}

func (x *Transcript) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcript) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_voicekit_proto protoreflect.FileDescriptor

const file_voicekit_proto_rawDesc = "" +
	"\n" +
	"\x0evoicekit.proto\x12\x16voicekit.recognizer.v1\"\x91\x01\n" +
	"\x10RecognizeRequest\x12A\n" +
	"\x06config\x18\x01 \x01(\v2'.voicekit.recognizer.v1.StreamingConfigH\x00R\x06config\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContentB\x13\n" +
	"\x11streaming_request\"\xca\x01\n" +
	"\x0fStreamingConfig\x12A\n" +
	"\bencoding\x18\x01 \x01(\x0e2%.voicekit.recognizer.v1.AudioEncodingR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12.\n" +
	"\x13audio_channel_count\x18\x03 \x01(\x05R\x11audioChannelCount\x12#\n" +
	"\rlanguage_code\x18\x04 \x01(\tR\flanguageCode\"l\n" +
	"\x11RecognizeResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".voicekit.recognizer.v1.TranscriptR\aresults\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\"@\n" +
	"\n" +
	"Transcript\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence*x\n" +
	"\rAudioEncoding\x12\x18\n" +
	"\x14ENCODING_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bLINEAR16\x10\x01\x12\t\n" +
	"\x05MULAW\x10\x02\x12\b\n" +
	"\x04ALAW\x10\x03\x12\f\n" +
	"\bRAW_OPUS\x10\x04\x12\x0e\n" +
	"\n" +
	"MPEG_AUDIO\x10\x05\x12\f\n" +
	"\bADTS_AAC\x10\x062w\n" +
	"\x0fVoiceRecognizer\x12d\n" +
	"\tRecognize\x12(.voicekit.recognizer.v1.RecognizeRequest\x1a).voicekit.recognizer.v1.RecognizeResponse(\x010\x01B(Z&voicekit-mock/pkg/api/recognizer/v1;pbb\x06proto3"

var (
	file_voicekit_proto_rawDescOnce sync.Once
	file_voicekit_proto_rawDescData []byte
)

func file_voicekit_proto_rawDescGZIP() []byte {
	file_voicekit_proto_rawDescOnce.Do(func() {
		file_voicekit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voicekit_proto_rawDesc), len(file_voicekit_proto_rawDesc)))
	})
	return file_voicekit_proto_rawDescData
}

var file_voicekit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_voicekit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_voicekit_proto_goTypes = []any{
	(AudioEncoding)(0),        // 0: voicekit.recognizer.v1.AudioEncoding
	(*RecognizeRequest)(nil),  // 1: voicekit.recognizer.v1.RecognizeRequest
	(*StreamingConfig)(nil),   // 2: voicekit.recognizer.v1.StreamingConfig
	(*RecognizeResponse)(nil), // 3: voicekit.recognizer.v1.RecognizeResponse
	(*Transcript)(nil),        // 4: voicekit.recognizer.v1.Transcript
}
var file_voicekit_proto_depIdxs = []int32{
	2, // 0: voicekit.recognizer.v1.RecognizeRequest.config:type_name -> voicekit.recognizer.v1.StreamingConfig
	0, // 1: voicekit.recognizer.v1.StreamingConfig.encoding:type_name -> voicekit.recognizer.v1.AudioEncoding
	4, // 2: voicekit.recognizer.v1.RecognizeResponse.results:type_name -> voicekit.recognizer.v1.Transcript
	1, // 3: voicekit.recognizer.v1.VoiceRecognizer.Recognize:input_type -> voicekit.recognizer.v1.RecognizeRequest
	3, // 4: voicekit.recognizer.v1.VoiceRecognizer.Recognize:output_type -> voicekit.recognizer.v1.RecognizeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_voicekit_proto_init() }
func file_voicekit_proto_init() {
	if File_voicekit_proto != nil {
		return
	}
	file_voicekit_proto_msgTypes[0].OneofWrappers = []any{
		(*RecognizeRequest_Config)(nil),
		(*RecognizeRequest_AudioContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voicekit_proto_rawDesc), len(file_voicekit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voicekit_proto_goTypes,
		DependencyIndexes: file_voicekit_proto_depIdxs,
		EnumInfos:         file_voicekit_proto_enumTypes,
		MessageInfos:      file_voicekit_proto_msgTypes,
	}.Build()
	File_voicekit_proto = out.File
	file_voicekit_proto_goTypes = nil
	file_voicekit_proto_depIdxs = nil
}
