// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: voicekit.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceRecognizer_Recognize_FullMethodName = "/voicekit.recognizer.v1.VoiceRecognizer/Recognize"
)

// VoiceRecognizerClient is the client API for VoiceRecognizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceRecognizerClient interface {
	Recognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse], error)
}

type voiceRecognizerClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceRecognizerClient(cc grpc.ClientConnInterface) VoiceRecognizerClient {
	return &voiceRecognizerClient{cc}
}

func (c *voiceRecognizerClient) Recognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceRecognizer_ServiceDesc.Streams[0], VoiceRecognizer_Recognize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecognizeRequest, RecognizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceRecognizer_RecognizeClient = grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse]

// VoiceRecognizerServer is the server API for VoiceRecognizer service.
// All implementations must embed UnimplementedVoiceRecognizerServer
// for forward compatibility.
type VoiceRecognizerServer interface {
	Recognize(grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]) error
	mustEmbedUnimplementedVoiceRecognizerServer()
}

// UnimplementedVoiceRecognizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceRecognizerServer struct{}

func (UnimplementedVoiceRecognizerServer) Recognize(grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedVoiceRecognizerServer) mustEmbedUnimplementedVoiceRecognizerServer() {}
func (UnimplementedVoiceRecognizerServer) testEmbeddedByValue()                         {}

// UnsafeVoiceRecognizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceRecognizerServer will
// result in compilation errors.
type UnsafeVoiceRecognizerServer interface {
	mustEmbedUnimplementedVoiceRecognizerServer()
}

func RegisterVoiceRecognizerServer(s grpc.ServiceRegistrar, srv VoiceRecognizerServer) {
	// If the following call pancis, it indicates UnimplementedVoiceRecognizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceRecognizer_ServiceDesc, srv)
}

func _VoiceRecognizer_Recognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceRecognizerServer).Recognize(&grpc.GenericServerStream[RecognizeRequest, RecognizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceRecognizer_RecognizeServer = grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]

// VoiceRecognizer_ServiceDesc is the grpc.ServiceDesc for VoiceRecognizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceRecognizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voicekit.recognizer.v1.VoiceRecognizer",
	HandlerType: (*VoiceRecognizerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Recognize",
			Handler:       _VoiceRecognizer_Recognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "voicekit.proto",
}
